spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/practice-security;
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: none #create update none
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: info
    org.hibernate.SQL: debug
    org.hibernate.type: debug